"""
Agent Model
Represents registered agent instances with metadata and status tracking.
"""
from typing import Optional
from datetime import datetime
from sqlalchemy import String, ForeignKey, DateTime, Integer, Float, SmallInteger
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base
from app.models.mixins import UUIDMixin, TimestampMixin
from app.constants.constants import AgentStatus


class Agent(Base, UUIDMixin, TimestampMixin):
    """
    Registered agent instances.
    Tracks agent metadata, status, and heartbeat for monitoring.
    """
    __tablename__ = "agents"

    # Unique agent identifier (generated by agent on first run)
    agent_id: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    
    # Links to API key used for authentication
    api_key_id: Mapped[Optional[str]] = mapped_column(ForeignKey("agent_api_keys.id"), nullable=True)
    
    # Owner
    user_id: Mapped[str] = mapped_column(ForeignKey("users.id"), nullable=False, index=True)
    
    # Metadata
    name: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)  # User-friendly name
    hostname: Mapped[str] = mapped_column(String(255), nullable=False)
    platform: Mapped[str] = mapped_column(String(50), nullable=False)  # "Windows", "Linux", "Darwin"
    version: Mapped[str] = mapped_column(String(20), nullable=False)  # Agent version
    
    # Status tracking
    status: Mapped[int] = mapped_column(SmallInteger, default=AgentStatus.OFFLINE.value, index=True)
    last_heartbeat: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    last_task_id: Mapped[Optional[str]] = mapped_column(ForeignKey("agent_forge_tasks.id"), nullable=True)
    
    # Performance metrics
    total_tasks_assigned: Mapped[int] = mapped_column(Integer, default=0)
    total_tasks_completed: Mapped[int] = mapped_column(Integer, default=0)
    total_tasks_failed: Mapped[int] = mapped_column(Integer, default=0)
    success_rate: Mapped[float] = mapped_column(Float, default=0.0)
    total_execution_time_seconds: Mapped[int] = mapped_column(Integer, default=0)
    average_execution_time_seconds: Mapped[float] = mapped_column(Float, default=0.0)
    last_task_completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Rate limiting
    max_tasks_per_hour: Mapped[int] = mapped_column(Integer, default=60)
    tasks_this_hour: Mapped[int] = mapped_column(Integer, default=0)
    rate_limit_reset_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="agents")
    api_key: Mapped[Optional["AgentAPIKey"]] = relationship("AgentAPIKey", back_populates="agents")
    tasks: Mapped[list["AgentForgeTask"]] = relationship(
        "AgentForgeTask", 
        back_populates="assigned_agent",
        foreign_keys="[AgentForgeTask.assigned_agent_id]"
    )

    def __repr__(self) -> str:
        return f"<Agent(id={self.id}, hostname={self.hostname}, status={self.status})>"
